%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-depthai-examples
Version:        3.0.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS depthai_examples package

License:        MIT
Source0:        %{name}-%{version}.tar.gz

Requires:       opencv-devel
Requires:       ros-kilted-backward-ros
Requires:       ros-kilted-camera-info-manager
Requires:       ros-kilted-cv-bridge
Requires:       ros-kilted-depth-image-proc
Requires:       ros-kilted-depthai
Requires:       ros-kilted-depthai-bridge
Requires:       ros-kilted-depthai-descriptions
Requires:       ros-kilted-depthai-ros-msgs
Requires:       ros-kilted-foxglove-msgs
Requires:       ros-kilted-image-transport
Requires:       ros-kilted-rclcpp
Requires:       ros-kilted-robot-state-publisher
Requires:       ros-kilted-ros-environment
Requires:       ros-kilted-rviz-imu-plugin
Requires:       ros-kilted-sensor-msgs
Requires:       ros-kilted-std-msgs
Requires:       ros-kilted-stereo-msgs
Requires:       ros-kilted-vision-msgs
Requires:       ros-kilted-xacro
Requires:       ros-kilted-ros-workspace
BuildRequires:  opencv-devel
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-backward-ros
BuildRequires:  ros-kilted-camera-info-manager
BuildRequires:  ros-kilted-cv-bridge
BuildRequires:  ros-kilted-depthai
BuildRequires:  ros-kilted-depthai-bridge
BuildRequires:  ros-kilted-depthai-descriptions
BuildRequires:  ros-kilted-depthai-ros-msgs
BuildRequires:  ros-kilted-foxglove-msgs
BuildRequires:  ros-kilted-image-transport
BuildRequires:  ros-kilted-rclcpp
BuildRequires:  ros-kilted-ros-environment
BuildRequires:  ros-kilted-rviz-imu-plugin
BuildRequires:  ros-kilted-sensor-msgs
BuildRequires:  ros-kilted-std-msgs
BuildRequires:  ros-kilted-stereo-msgs
BuildRequires:  ros-kilted-vision-msgs
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
The depthai_examples package

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Thu Jul 31 2025 Adam Serafin <adam.serafin@luxonis.com> - 3.0.0-1
- Autogenerated by Bloom

