%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/iron/.*$
%global __requires_exclude_from ^/opt/ros/iron/.*$

Name:           ros-iron-depthai-ros-driver
Version:        2.8.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS depthai_ros_driver package

License:        MIT
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-iron-ament-cmake-auto
Requires:       ros-iron-camera-calibration
Requires:       ros-iron-cv-bridge
Requires:       ros-iron-depthai
Requires:       ros-iron-depthai-bridge
Requires:       ros-iron-depthai-descriptions
Requires:       ros-iron-depthai-examples
Requires:       ros-iron-depthai-ros-msgs
Requires:       ros-iron-diagnostic-msgs
Requires:       ros-iron-diagnostic-updater
Requires:       ros-iron-image-pipeline
Requires:       ros-iron-image-transport
Requires:       ros-iron-image-transport-plugins
Requires:       ros-iron-pluginlib
Requires:       ros-iron-rclcpp
Requires:       ros-iron-rclcpp-components
Requires:       ros-iron-sensor-msgs
Requires:       ros-iron-std-msgs
Requires:       ros-iron-std-srvs
Requires:       ros-iron-vision-msgs
Requires:       ros-iron-ros-workspace
BuildRequires:  ros-iron-ament-cmake
BuildRequires:  ros-iron-ament-cmake-auto
BuildRequires:  ros-iron-camera-calibration
BuildRequires:  ros-iron-cv-bridge
BuildRequires:  ros-iron-depthai
BuildRequires:  ros-iron-depthai-bridge
BuildRequires:  ros-iron-depthai-descriptions
BuildRequires:  ros-iron-depthai-examples
BuildRequires:  ros-iron-depthai-ros-msgs
BuildRequires:  ros-iron-diagnostic-msgs
BuildRequires:  ros-iron-diagnostic-updater
BuildRequires:  ros-iron-image-pipeline
BuildRequires:  ros-iron-image-transport
BuildRequires:  ros-iron-image-transport-plugins
BuildRequires:  ros-iron-pluginlib
BuildRequires:  ros-iron-rclcpp
BuildRequires:  ros-iron-rclcpp-components
BuildRequires:  ros-iron-sensor-msgs
BuildRequires:  ros-iron-std-msgs
BuildRequires:  ros-iron-std-srvs
BuildRequires:  ros-iron-vision-msgs
BuildRequires:  ros-iron-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Depthai ROS Monolithic node.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/iron" \
    -DAMENT_PREFIX_PATH="/opt/ros/iron" \
    -DCMAKE_PREFIX_PATH="/opt/ros/iron" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/iron

%changelog
* Fri Sep 15 2023 Adam Serafin <adam.serafin@luxonis.com> - 2.8.1-1
- Autogenerated by Bloom

* Thu Sep 07 2023 Adam Serafin <adam.serafin@luxonis.com> - 2.8.0-1
- Autogenerated by Bloom

* Fri Aug 11 2023 Adam Serafin <adam.serafin@luxonis.com> - 2.7.5-1
- Autogenerated by Bloom

* Mon Jun 26 2023 Adam Serafin <adam.serafin@luxonis.com> - 2.7.4-1
- Autogenerated by Bloom

