/oak:
  ros__parameters:
    pipeline_gen:
      i_nn_type: rgb
      i_pipeline_type: rgb
    nn:
      i_nn_family: segmentation
      i_nn_model: luxonis/deeplab-v3-plus:256x256
      i_enable_passthrough: true


